{{- if and (not .Values.credentials.existingSecret) .Values.credentials.inlineKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inworld-tts.fullname" . }}-gcp-credentials
  labels:
    {{- include "inworld-tts.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.credentials.existingSecretKey }}: {{ .Values.credentials.inlineKey | toString | trim | quote }}
{{- end }}
